#Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feedback
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
# Gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: nanhukumari@gmail.com
    password: 9001869109
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    templates:
      path: mail-templates

#  security:
#    user:
#      password: password
#      name: feedback
debug: true



