#Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feedback
    username: root
    password: ENC(BqkxEbyBDSyIJ/pnT8BUPSpAXUihmbOy)
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  # Gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: nanhukumari@gmail.com
    password: ENC(Ig8OwX+RPf8Gl6PADPsoFkZAvH7axM7I)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    templates:
      path: mail-templates

#Password encryption
jasypt:
  encryptor:
    password: everest
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


